services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sws_app
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - sws_network

  nginx:
    image: nginx:alpine
    container_name: sws_nginx
    restart: unless-stopped
    ports:
      - "7080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - sws_network

  db:
    image: mysql:8.0
    container_name: sws_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootadmin
      MYSQL_DATABASE: sws_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "7306:3306"
    networks:
      - sws_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sws_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: admin
      PMA_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: rootadmin
    ports:
      - "7081:80"
    depends_on:
      - db
    networks:
      - sws_network

  redis:
    image: redis:7-alpine
    container_name: sws_redis
    restart: always
    ports:
      - "7379:6379"
    networks:
      - sws_network

networks:
  sws_network:
    driver: bridge

volumes:
  db_data: